version: "2"
run:
  tests: false
linters:
  enable:
    - misspell
    - unconvert
  disable:
    - dupl
    - gocritic
    - gocyclo
    - gosec
    - lll
    - unparam
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
    staticcheck:
      checks:
        - all
        - -QF1001
        - -ST1005
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - gocritic
          - gocyclo
          - gosec
          - lll
          - staticcheck
          - unparam
        path: _test\.go$
      - linters:
          - dupl
          - errcheck
          - gocritic
          - gocyclo
          - gosec
          - lll
          - staticcheck
          - unparam
          - unused
        path: ^examples/
      - linters:
          - errcheck
          - gocritic
          - gocyclo
          - gosec
          - lll
          - staticcheck
          - unparam
        path: ^tests/
      - linters:
          - errcheck
        path: cmd/
      - linters:
          - unparam
        path: internal/
      - linters:
          - errcheck
        text: Error return value is not checked
        source: defer.*\{.*_ =
      - linters:
          - unparam
        text: '- `ctx` is unused'
      - linters:
          - staticcheck
        text: SA1019.*PreferServerCipherSuites
      - linters:
          - staticcheck
        text: (QF1001|ST1005)
      - linters:
          - lll
        path: (generated|_gen\.go|config\.go)
      - linters:
          - gocyclo
        text: (NewServer|Close|startServer|tailLogFile)
      - linters:
          - dupl
        path: internal/datasource/
      - linters:
          - lll
        source: (fmt\.Errorf|errors\.New|return.*fmt\.Sprintf|SELECT|INSERT|UPDATE|DELETE)
      - linters:
          - gosec
        text: G104.*
        source: (Close|Flush|Write|Print)
      - path: (.+)\.go$
        text: SA1019.*PreferServerCipherSuites
      - path: (.+)\.go$
        text: QF1001.*De Morgan
      - path: (.+)\.go$
        text: ST1005.*error strings should not be capitalized
    paths:
      - examples
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
