version: 2

run:
  timeout: 10m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
  exclusions:
    paths:
      - vendor
      - venv
      - bin
      - build
      - tests
      - examples
      - ".*_test\\.go$"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Allow deprecated TLS cipher preference (kept for compatibility)
    - text: "PreferServerCipherSuites"
      linters:
        - staticcheck
    # Allow Let's Encrypt capitalization  
    - text: "Let's Encrypt"
      linters:
        - staticcheck

