run:
  timeout: 10m
  tests: false

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - unconvert
    - unused
    - staticcheck
  disable:
    - gosec    # Too many false positives (G104 duplicates errcheck, hardcoded credentials in tests, etc.)
    - unparam  # Too noisy, many false positives for interface implementations
    - dupl     # Duplicate code is often intentional in database/datasource code
    - lll      # Line length is not critical
    - gocyclo  # Cyclomatic complexity is not critical
    - gocritic # Code style suggestions that aren't critical

linters-settings:
  errcheck:
    check-blank: false  # Don't report errors on blank identifier assignments
    check-type-assertions: false
  staticcheck:
    checks: ["all", "-ST1005", "-QF1001"]  # Disable style checks that aren't critical

issues:
  exclude-dirs:
    - examples
  exclude:
    - "SA1019.*PreferServerCipherSuites"
    - "QF1001.*De Morgan"
    - "ST1005.*error strings should not be capitalized"
  exclude-rules:
    # Exclude test files from strict linting - test code is less critical
    - path: _test\.go$
      linters:
        - errcheck
        - dupl
        - gosec
        - gocyclo
        - unparam
        - lll
        - gocritic
        - staticcheck

    # Exclude example code from strict linting
    - path: ^examples/
      linters:
        - errcheck
        - gosec
        - unparam
        - unused
        - lll
        - dupl
        - gocritic
        - staticcheck
        - gocyclo

    # Exclude test scripts from strict linting
    - path: ^tests/
      linters:
        - errcheck
        - gosec
        - unparam
        - lll
        - gocyclo
        - gocritic
        - staticcheck

    # Exclude errcheck from CLI commands - print errors are not critical
    - path: cmd/
      linters:
        - errcheck

    # Exclude unparam from internal implementations - often interface requirements
    - path: internal/
      linters:
        - unparam

    # Exclude intentional blank error assignments (defer cleanup, best effort)
    - linters:
        - errcheck
      text: "Error return value is not checked"
      source: "defer.*\\{.*_ ="

    # Exclude unused context parameters (common in interface implementations)
    - linters:
        - unparam
      text: "- `ctx` is unused"

    # Exclude deprecated TLS PreferServerCipherSuites (Go 1.18+) - kept for compatibility
    - linters:
        - staticcheck
      text: "SA1019.*PreferServerCipherSuites"

    # Exclude staticcheck style suggestions that aren't critical
    - linters:
        - staticcheck
      text: "(QF1001|ST1005)"

    # Exclude line length in generated or config code
    - linters:
        - lll
      path: "(generated|_gen\\.go|config\\.go)"

    # Exclude cyclomatic complexity for initialization and cleanup functions
    - linters:
        - gocyclo
      text: "(NewServer|Close|startServer|tailLogFile)"

    # Exclude duplicate code detection - often legitimate similar patterns
    - linters:
        - dupl
      path: internal/datasource/

    # Exclude line length for long error messages and SQL queries
    - linters:
        - lll
      source: "(fmt\\.Errorf|errors\\.New|return.*fmt\\.Sprintf|SELECT|INSERT|UPDATE|DELETE)"

    # Exclude gosec G104 (unhandled errors) for print/close functions
    - linters:
        - gosec
      text: "G104.*"
      source: "(Close|Flush|Write|Print)"
