version: "2"

run:
  timeout: 10m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - (io.Writer).Write
        - (*text/tabwriter.Writer).Flush
        - (net.Conn).Close
        - (io.Closer).Close
        - os.Setenv
        - os.Unsetenv
        - os.Chdir
        - os.Remove
        - os.RemoveAll
        - (*os.File).Close
    staticcheck:
      checks:
        - "all"
        - "-ST1005"   # Error strings should not be capitalized
        - "-ST1023"   # Should omit type from declaration
        - "-QF1001"   # Could apply De Morgan's law
        - "-QF1002"   # Could use tagged switch
        - "-QF1003"   # Could use tagged switch
        - "-QF1004"   # Could use strings.ReplaceAll
        - "-QF1008"   # Could remove embedded field from selector
        - "-SA1019"   # Deprecated (PreferServerCipherSuites)
  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
    rules:
      - path: "_test\\.go$"
        linters:
          - errcheck
      - path: "vendor/"
        linters:
          - errcheck
          - govet
          - staticcheck
          - unused
          - ineffassign
      - path: "examples/"
        linters:
          - errcheck
          - govet
          - staticcheck
          - unused
          - ineffassign
