version: "2"

run:
  timeout: 10m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - gosec
    - misspell
    - unconvert
    - unparam
    - unused
    - gocritic
    - gocyclo
    - dupl
    - lll
    - whitespace

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: false

issues:
  exclude-rules:
    # Exclude test files from errcheck - test error handling is less critical
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gosec
        - gocyclo
    
    # Exclude common acceptable error ignores
    - linters:
        - errcheck
      text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*print(f|ln)?|os\\.(Un)?Setenv). is not checked"
