version: '3.8'

services:
  elemta:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elemta
    restart: unless-stopped
    ports:
      - "2525:2525"
    volumes:
      - elemta_queue:/app/queue
      - elemta_logs:/app/logs
      - elemta_config:/app/config
      - elemta_plugins:/app/plugins
    environment:
      - TZ=UTC
    networks:
      - elemta_network

networks:
  elemta_network:
    driver: bridge

volumes:
  elemta_queue:
    driver: local
  elemta_logs:
    driver: local
  elemta_config:
    driver: local
  elemta_plugins:
    driver: local 