version: '3.8'

services:
  elemta:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elemta
    restart: unless-stopped
    ports:
      - "2525:25"
      - "8081:8080"
    volumes:
      - elemta_queue:/app/queue
      - elemta_logs:/app/logs
      - elemta_config:/app/config
      - elemta_plugins:/app/plugins
    environment:
      - TZ=UTC
      - DEBUG=true
    tty: true
    stdin_open: true
    init: true
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - elemta_network
    depends_on:
      - elemta-clamav
      - elemta-rspamd

  elemta-clamav:
    image: clamav/clamav:latest
    container_name: elemta-clamav
    restart: unless-stopped
    networks:
      - elemta_network
    volumes:
      - clamav_data:/var/lib/clamav
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3310"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  elemta-rspamd:
    image: rspamd/rspamd:latest
    container_name: elemta-rspamd
    restart: unless-stopped
    networks:
      - elemta_network
    volumes:
      - rspamd_data:/var/lib/rspamd
    ports:
      - "11334:11334"  # Web interface
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11334/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

networks:
  elemta_network:
    driver: bridge

volumes:
  elemta_queue:
    driver: local
  elemta_logs:
    driver: local
  elemta_config:
    driver: local
  elemta_plugins:
    driver: local
  clamav_data:
    driver: local
  rspamd_data:
    driver: local 