version: '3.8'

services:
  elemta:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elemta
    restart: unless-stopped
    ports:
      - "2525:2525"
    volumes:
      - elemta_queue:/app/queue
      - elemta_logs:/app/logs
      - elemta_config:/app/config
      - elemta_plugins:/app/plugins
      - ./config:/config-volume
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
    environment:
      - TZ=UTC
      - ELEMTA_CONFIG_PATH=/config-volume/elemta.conf
      - DEBUG=true
    entrypoint: ["/docker-entrypoint.sh"]
    tty: true
    stdin_open: true
    init: true
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2525"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - elemta_network

networks:
  elemta_network:
    driver: bridge

volumes:
  elemta_queue:
    driver: local
  elemta_logs:
    driver: local
  elemta_config:
    driver: local
  elemta_plugins:
    driver: local 