smtp:
  listen_address: "0.0.0.0"
  port: 2525  # Using a non-privileged port for testing
  hostname: "localhost"
  max_connections: 100
  max_message_size: 52428800  # 50MB
  allow_insecure_auth: true
  timeouts:
    connection: 60
    command: 30
    data: 300
    idle: 300

queue:
  path: "queue"
  max_size: 1073741824  # 1GB
  retry_interval: 300  # 5 minutes
  max_retries: 10
  cleanup_interval: 3600  # 1 hour

rules:
  path: "rules"
  script_path: "scripts"

logging:
  level: "debug"
  format: "text"
  path: "logs"

metrics:
  enabled: false
  address: "0.0.0.0"
  port: 9090

web:
  enabled: false
  address: "0.0.0.0"
  port: 8080
  tls: false 