filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'
  processors:
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"
    - decode_json_fields:
        fields: ["message"]
        target: "elemta"
        when:
          and:
            - contains:
                message: '{"time":'
            - equals:
                container.name: "elemta-node0"
  fields:
    elemta_service: elemta
    log_type: container
  fields_under_root: true

- type: log
  enabled: true
  paths:
    - /var/log/elemta/*.log
  fields:
    elemta_service: elemta
    log_type: file
  fields_under_root: true
  multiline.pattern: '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}'
  multiline.negate: true
  multiline.match: after

processors:
- add_host_metadata:
    when.not.contains.tags: forwarded
- add_docker_metadata: ~
- add_kubernetes_metadata: ~

output.elasticsearch:
  hosts: ["elemta-elasticsearch:9200"]
  index: "%{[container.name]}-%{+yyyy.MM.dd}"

setup.kibana:
  host: "elemta-kibana:5601"

setup.template.name: "elemta-containers"
setup.template.pattern: "elemta-*"
setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644 