apiVersion: v1
kind: ConfigMap
metadata:
  name: elemta-config
data:
  elemta.conf: |
    [general]
    hostname = "mail.example.com"
    log_level = "info"

    [smtp]
    enabled = true
    address = "0.0.0.0:2525"

    [auth]
    enabled = true
    required = true 