apiVersion: v1
data:
  elemta.conf: |
    [general]
    hostname = "mail.example.com"
    log_level = "info"

    [smtp]
    enabled = true
    address = "0.0.0.0:2525"

    [auth]
    enabled = true
    required = true
  auth.datasource.type: sqlite
  auth.sqlite.path: /app/config/auth.db
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: elemta-config
