apiVersion: v1
kind: ConfigMap
metadata:
  name: rspamd-config
data:
  worker-normal.inc: |
    # Settings for the normal worker (protocol interface)
    bind_socket = "0.0.0.0:11333";
    
    # Allow connections from any IP
    secure_ip = null;
    
    # Disable password protection for testing
    password = null;
    
    # Enable extended protocol
    enable_password = null;
    
    # Increase timeout for better reliability
    timeout = 60s;
    
  worker-controller.inc: |
    # Settings for the controller worker (web interface)
    bind_socket = "0.0.0.0:11334";
    
    # Allow connections from any IP
    secure_ip = null;
    
    # Disable password protection for testing
    password = null;
    
    # Enable extended protocol
    enable_password = null;
    
    # Increase timeout for better reliability
    timeout = 60s; 