apiVersion: v1
kind: Service
metadata:
  name: elemta
  labels:
    app: elemta
spec:
  type: NodePort
  ports:
  - port: 25
    targetPort: 25
    nodePort: 30025
    protocol: TCP
    name: smtp
  selector:
    app: elemta 