apiVersion: v1
kind: Service
metadata:
  name: elemta
  labels:
    app: elemta
spec:
  type: ClusterIP
  ports:
  - port: 2525
    targetPort: 2525
    protocol: TCP
    name: smtp
  selector:
    app: elemta 