# Elemta Development Configuration
# Uses non-privileged ports for internal development/testing

server:
  hostname: "localhost"
  listen: ":2525"       # Non-privileged SMTP port
  max_size: 10485760    # 10MB
  timeout: 30
  auth_required: false
  tls: false

tls:
  enabled: false
  listen_addr: ":2465"  # Non-privileged SMTPS port
  cert_file: ""
  key_file: ""
  min_version: "tls1.2"
  enable_starttls: true

queue:
  dir: "./queue"
  max_size: 1000
  retry_delay: 300      # 5 minutes
  max_retries: 5
  cleanup_interval: 3600 # 1 hour

delivery:
  workers: 3
  timeout: 30
  retry_delay: 300
  max_retries: 3

plugins:
  dir: "./plugins"
  enabled: []

api:
  enabled: true
  listen_addr: "127.0.0.1:8025"  # Non-privileged web interface port
  auth_enabled: false
  web_root: "./web/static"

# Logging configuration
log:
  level: "debug"
  format: "json"
  file: ""  # Empty means stdout

# Metrics configuration  
metrics:
  enabled: true
  listen_addr: "127.0.0.1:9090"  # Prometheus metrics port 