# Elemta SMTP Server Configuration

[server]
hostname = "localhost"
listen = ":2525"
max_size = 26214400  # 25MB

# TLS Configuration - Enable STARTTLS
[tls]
enabled = true
enable_starttls = true
cert_file = "/app/certs/test.crt"
key_file = "/app/certs/test.key"

[queue]
dir = "/app/queue"

[logging]
type = "elastic"
level = "info"
format = "json"
output = "http://elemta-elasticsearch:9200"
options = { index = "elemta-logs", bufferSize = 50, flushInterval = "5s" }

[plugins]
directory = "/app/plugins"
enabled = []

[queue_processor]
enabled = true
interval = 10
workers = 5
debug = false

[auth] 
enabled = true
required = false
datasource_type = "ldap"
datasource_name = "ldap"
datasource_host = "elemta-ldap"
datasource_port = 389
datasource_user = "cn=admin,dc=example,dc=com"
datasource_pass = "admin"
datasource_db = "dc=example,dc=com"

[delivery]
mode = "lmtp"
host = "elemta-dovecot"
port = 2424
timeout = 30

[metrics]
enabled = true
listen_addr = ":8080"
