[server]
hostname = "mail.example.com"
listen = ":25"
tls = false
cert_file = "/etc/elemta/certs/example.com.crt"
key_file = "/etc/elemta/certs/example.com.key"

queue_dir = "/app/queue"

[logging]
level = "info"
format = "text"
file = "/app/logs/elemta.log"

[plugins]
directory = "/app/plugins"
enabled = ["greylisting", "spf", "dkim"]

[authentication]
required = false
type = "none"
