[server]
hostname = "mail.example.com"
listen = ":2525"
tls = false
cert_file = "/etc/elemta/certs/example.com.crt"
key_file = "/etc/elemta/certs/example.com.key"

queue_dir = "./queue"

[logging]
level = "info"
format = "text"
file = "./logs/elemta.log"

[plugins]
directory = "./plugins"
enabled = ["greylisting", "spf", "dkim"]

[authentication]
required = false
type = "none"

smtp:
  hostname: mail.example.com
  port: 2525
  devMode: true
  maxSize: 10485760
  sessionTimeout: 300s
  allowedRelays:
    - 127.0.0.1
    - "::1"
    - 192.168.65.1
  auth:
    enabled: true
    required: false
    provider: "file"
    file:
      path: "config/users.json"
