[server]
hostname = "mail.example.com"
listen = ":2525"
tls = false
cert_file = "/etc/elemta/certs/example.com.crt"
key_file = "/etc/elemta/certs/example.com.key"

queue_dir = "/app/queue"
max_size = 10485760  # 10MB message size limit

[logging]
level = "info"
format = "text"
file = "/app/logs/elemta.log"

[plugins]
directory = "/app/plugins"
enabled = ["greylisting", "spf", "dkim"]

[authentication]
required = false
type = "none"

[api]
enabled = true
listen_addr = "0.0.0.0:8081"

[delivery]
mode = "lmtp"  # Use LMTP protocol to deliver to Dovecot
host = "elemta-dovecot"
port = 1024
test_mode = true  # Enable test mode delivery
default_domain = "example.com"  # Default domain for local delivery

[test]
enabled = true
discard_real_delivery = false  # Don't discard, actually deliver
admin_email = "admin@example.com"
