# Elemta SMTP Server Configuration

[server]
hostname = "mail.example.com"
listen = ":2525"  # Internal SMTP port (non-privileged)
listen_submission = ":587"  # Submission port for authenticated clients
max_size = 26214400  # 25MB
local_domains = ["example.com", "mail.example.com", "localhost"]
dev_mode = true  # Enable development mode for XDEBUG command

# TLS Configuration - Enable STARTTLS
[tls]
enabled = true
enable_starttls = true
cert_file = "/app/certs/test.crt"
key_file = "/app/certs/test.key"

[queue]
dir = "/app/queue"

[logging]
type = "elastic"
level = "info"
format = "json"
output = "http://elemta-elasticsearch:9200"
options = { index = "elemta-logs", bufferSize = 50, flushInterval = "5s" }

[plugins]
directory = "/app/plugins"
enabled = ["rspamd", "clamav"]

[queue_processor]
enabled = true
interval = 10
workers = 5
debug = false

[auth] 
enabled = true
required = false
datasource_type = "ldap"
datasource_name = "ldap"
datasource_host = "elemta-ldap"
datasource_port = 389
datasource_user = "cn=admin,dc=example,dc=com"
datasource_pass = "admin"
datasource_db = "dc=example,dc=com"

[delivery]
mode = "lmtp"
host = "elemta-dovecot"
port = 2424
timeout = 30
max_retries = 3
retry_delay = 60

[memory]
max_memory_usage = 2147483648  # 2GB total memory limit
memory_warning_threshold = 0.75  # 75% warning threshold
memory_critical_threshold = 0.90  # 90% critical threshold
gc_threshold = 0.80  # 80% force garbage collection
monitoring_interval = 5  # Memory monitoring interval in seconds
per_connection_memory_limit = 52428800  # 50MB per session (ELE-16 requirement)
max_goroutines = 2000
goroutine_leak_detection = true
memory_exhaustion_protection = true

[resources]
max_connections = 1000
max_connections_per_ip = 50
connection_timeout = 30
session_timeout = 300
idle_timeout = 120
rate_limit_window = 60
max_requests_per_window = 1000  # Increased from 100 to 1000 for testing
goroutine_pool_size = 100
circuit_breaker_enabled = true
resource_monitoring_enabled = true

[metrics]
enabled = true
listen_addr = ":8080"
