[server]
hostname = "mail.example.com"
listen = ":2525"
tls = false
cert_file = "/etc/elemta/certs/example.com.crt"
key_file = "/etc/elemta/certs/example.com.key"

queue_dir = "./queue"

[logging]
level = "info"
format = "text"
file = "./logs/elemta.log"

[plugins]
directory = "./plugins"
enabled = ["greylisting", "spf", "dkim"]

[authentication]
required = false
type = "none"
