# Elemta SMTP Server Configuration

[server]
hostname = "localhost"
listen = ":2525"
tls = false
cert_file = ""
key_file = ""

queue_dir = "/app/queue"

[logging]
level = "info"
format = "text"
file = ""

[plugins]
directory = "/app/plugins"
enabled = []

[queue_processor]
enabled = true
interval = 10
workers = 5
debug = false

# TLS Configuration (uncomment and configure as needed)
# [tls]
# enabled = false
# enable_starttls = true

# Authentication Configuration (uncomment and configure as needed)
# [auth] 
# enabled = false
# required = false
# datasource_type = "file"

# Delivery Configuration (uncomment and configure as needed)
# [delivery]
# mode = "smtp"
# timeout = 30
