# Elemta SMTP Server Configuration

[server]
hostname = "localhost"
listen = ":2525"
tls = false
cert_file = ""
key_file = ""
max_size = 26214400  # 25MB

[queue]
dir = "/app/queue"

[logging]
level = "debug"
format = "text"
file = ""

[plugins]
directory = "/app/plugins"
enabled = []

[queue_processor]
enabled = true
interval = 10
workers = 5
debug = false

[auth] 
enabled = false
required = false
datasource_type = "file"
datasource_path = "/app/config/users.txt"

[delivery]
mode = "lmtp"
host = "elemta-dovecot"
port = 2424
timeout = 30
