global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'elemta'
    scrape_interval: 5s
    static_configs:
      - targets: ['elemta:8080']
        labels:
          instance: 'elemta-server'

  - job_name: 'rspamd'
    scrape_interval: 5s
    static_configs:
      - targets: ['rspamd:11334']
        labels:
          instance: 'rspamd-server'

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
