global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - 'alert_rules.yml'

scrape_configs:
  - job_name: 'elemta'
    static_configs:
      - targets: ['elemta-metrics:8080']
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
