#!/bin/bash

# Script to create a simple queue entry using shell commands

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${YELLOW}Creating a Simple Queue Entry for Elemta${NC}"
echo "======================================"

# Generate a message ID (UUID format)
MSG_ID=$(cat /dev/urandom | tr -dc 'a-f0-9' | fold -w 8 | head -n 1)
MSG_ID="${MSG_ID}-$(cat /dev/urandom | tr -dc 'a-f0-9' | fold -w 4 | head -n 1)"
MSG_ID="${MSG_ID}-$(cat /dev/urandom | tr -dc 'a-f0-9' | fold -w 4 | head -n 1)"
MSG_ID="${MSG_ID}-$(cat /dev/urandom | tr -dc 'a-f0-9' | fold -w 4 | head -n 1)"
MSG_ID="${MSG_ID}-$(cat /dev/urandom | tr -dc 'a-f0-9' | fold -w 12 | head -n 1)"

QUEUE_TYPE="active"
SENDER="sender@example.com"
RECIPIENT="recipient@example.com"
SUBJECT="Test Message"
TIMESTAMP=$(date +%s)
CURRENT_TIME=$(date -u +"%Y-%m-%dT%H:%M:%S.%NZ")
EXPIRY_TIME=$(date -u -d "+7 days" +"%Y-%m-%dT%H:%M:%S.%NZ")

echo -e "${YELLOW}Creating message with ID: ${MSG_ID}${NC}"

# Create message content
MESSAGE="From: ${SENDER}
To: ${RECIPIENT}
Subject: ${SUBJECT}
Message-ID: <${MSG_ID}@example.com>
Date: $(date -R)

This is a test message for the ${QUEUE_TYPE} queue.
This message was generated by the Elemta queue simulator.
"

# Create data file
echo -e "${YELLOW}Creating data file...${NC}"
docker exec elemta-cli mkdir -p /app/queue/data
echo "$MESSAGE" | docker exec -i elemta-cli bash -c "cat > /app/queue/data/${MSG_ID}.eml"

# Create metadata file
echo -e "${YELLOW}Creating metadata file...${NC}"
docker exec elemta-cli mkdir -p /app/queue/${QUEUE_TYPE}

# Create metadata JSON
METADATA="{\"id\":\"${MSG_ID}\",\"from\":\"${SENDER}\",\"to\":[\"${RECIPIENT}\"],\"status\":\"queued\",\"created_at\":\"${CURRENT_TIME}\",\"updated_at\":\"${CURRENT_TIME}\",\"size\":${#MESSAGE},\"received_at\":\"${CURRENT_TIME}\",\"retry\":{\"attempts\":1,\"last_attempt\":\"${CURRENT_TIME}\",\"next_attempt\":\"${CURRENT_TIME}\",\"last_error\":\"\"},\"priority\":1,\"queue_type\":\"${QUEUE_TYPE}\",\"retry_count\":1,\"next_retry\":\"${CURRENT_TIME}\",\"last_error\":\"\",\"attempts\":[],\"delivery_status\":{\"${RECIPIENT}\":{\"status\":\"queued\",\"last_attempt\":\"${CURRENT_TIME}\",\"retry_count\":0,\"next_retry\":\"${CURRENT_TIME}\",\"dsn_sent\":false}},\"last_delivery_attempt\":\"${CURRENT_TIME}\",\"first_attempt_time\":\"${CURRENT_TIME}\",\"expiry_time\":\"${EXPIRY_TIME}\",\"dsn\":false}"

echo "$METADATA" | docker exec -i elemta-cli bash -c "cat > /app/queue/${QUEUE_TYPE}/${MSG_ID}.json"

echo -e "${GREEN}Created ${QUEUE_TYPE} message with ID ${MSG_ID}${NC}"

# Check queue statistics
echo -e "\n${YELLOW}Checking queue statistics:${NC}"
./scripts/elemta-cli.sh queue -config /app/config/elemta.toml stats

# List messages in the queue
echo -e "\n${YELLOW}Listing messages in the queue:${NC}"
./scripts/elemta-cli.sh queue -config /app/config/elemta.toml list

echo -e "\n${GREEN}Queue entry creation complete!${NC}" 