apiVersion: 1

groups:
  - name: Elemta Alerts
    folder: Elemta
    interval: 1m
    rules:
      - uid: high_active_connections
        title: High Active Connections
        condition: A
        data:
          - refId: A
            datasourceUid: Prometheus
            model:
              expr: elemta_connections_active > 100
              intervalMs: 60000
              maxDataPoints: 43200
              relativeTimeRange:
                from: 600
                to: 0
        noDataState: OK
        execErrState: Alerting
        for: 5m
        annotations:
          summary: High number of active connections
          description: There are more than 100 active connections for more than 5 minutes.
        labels:
          severity: warning

      - uid: queue_size_growing
        title: Queue Size Growing
        condition: A
        data:
          - refId: A
            datasourceUid: Prometheus
            model:
              expr: sum(elemta_queue_size) > 1000
              intervalMs: 60000
              maxDataPoints: 43200
              relativeTimeRange:
                from: 600
                to: 0
        noDataState: OK
        execErrState: Alerting
        for: 10m
        annotations:
          summary: Queue size is growing
          description: The total queue size is greater than 1000 for more than 10 minutes.
        labels:
          severity: warning

      - uid: high_delivery_failure_rate
        title: High Delivery Failure Rate
        condition: A
        data:
          - refId: A
            datasourceUid: Prometheus
            model:
              expr: elemta_delivery_failures_total / elemta_delivery_attempts_total > 0.2
              intervalMs: 60000
              maxDataPoints: 43200
              relativeTimeRange:
                from: 600
                to: 0
        noDataState: OK
        execErrState: Alerting
        for: 15m
        annotations:
          summary: High delivery failure rate
          description: The delivery failure rate is greater than 20% for more than 15 minutes.
        labels:
          severity: critical
